### PR TITLE
First attempt at automated release bulids

### PR DESCRIPTION
**Pull request by dagit**

### CODE REVIEW

**Comment by dagit** [comment]
This took a lot of fiddling to get it right and unfortunately I had to let it make releases to see how things were going to work out. So I apologize for the weird tags/releases that it made along the way. Hopefully @squid-man you can clean those up. I don't think I have the right permissions to do that.

The way this is supposed to work (and I hope I got all the cases right):

  * When we push to `develop` it makes a release named `develop <version number>` and tags it as a pre-release (I don't know how obvious that tagging is to users looking at the release section)
  * When we push to `master` it makes a **draft** release named `Release <version number>`
  * It also tries to build a changelog and I don't know how to disable that. Here is the documentation https://github.com/marketplace/actions/automatic-releases
  * It uploads 3 zip files: `MegaMan2Randomizer2-<os>-x64.zip` where `<os>` is `win`, `osx`, and `linux`. 

I made the releases in `master` drafts so we could review them if you want. But I figured for the `develop` branch we just them all to be pre-release candidates and there would be a lot more so let's just fully automate that case. It's easy to change this behavior if you want some other logic.

It ignores all other pushing and merging.

Incidentally, the release build itself happens on an ubuntu machine and as far as I know that's fine. I needed to do a bit of scripting to build up the version number and linux scripting is the thing I know the best.

**Comment by dagit** [comment]
Also...you probably want to do this as a squash merge because I was just throwing up random commits as I debugged things 🤐

**Comment by dagit** [comment]
oh, I was able to clean up the releases it made but not the tags.

**Comment by squid-man** [comment]
This is cool!

**Pull request merged**
